sudo: false
language: python
python:
  - "2.7"
  - "pypy"
cache: apt
addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  # so that we can use conda to get scipy and bioconda to get bowtie
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then
      export PATH="$HOME/miniconda/bin:$PATH";
    fi
  - $HOME/miniconda/bin/conda update --yes conda
  - $HOME/miniconda/bin/conda conda config --add channels r
  - $HOME/miniconda/bin/conda conda config --add channels bioconda
  # debug message to diagnose issues with system python version
  - python -c "import sys; print(sys.version.lower())"
install:
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then
      $HOME/miniconda/bin/conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy;
    fi
  - $HOME/miniconda/bin/conda install --yes bowtie bowtie2
script: make
